Feature: Full text queries, term level queries and aggregations combined

  Scenario: Search for "California", filter on "Meatballs", and get topping counts
    Given all pizzas is indexed
    When i make a dsl query
    """
    {
       "aggs":{
          "facets":{
             "filter":{
                "bool":{
                   "must":[
                      {
                         "query":{
                            "match":{
                               "name":"California"
                            }
                         }
                      },
                      {
                         "query":{
                            "term":{
                               "topping":"Meatballs"
                            }
                         }
                      }
                   ]
                }
             },
             "aggs":{
                "toppings":{
                   "terms":{
                      "field":"topping"
                   }
                }
             }
          }
       },
       "post_filter":{
          "bool":{
             "must":[
                {
                   "query":{
                      "match":{
                         "name":"California"
                      }
                   }
                },
                {
                   "query":{
                      "term":{
                         "topping":"Meatballs"
                      }
                   }
                }
             ]
          }
       }
    }
    """
    Then the response should contain
    """
    {
       "hits":{
          "total":1,
          "hits":[
             {
                "_source":{
                    "name":"California Meatballs"
                }
             }
          ]
       },
       "aggregations":{
          "facets":{
             "doc_count":1,
             "toppings":{
                "buckets":[
                   {
                      "key":"Meatballs",
                      "doc_count":1
                   }
                ]
             }
          }
       }
    }
    """